### ISSUE TITLE
Test of Unterminated comment is not valid

### ISSUE THREAD

**Issue by xpavlic** [galloj/IFJ22_Tester#13]
Test of Unterminated comment is not valid since block comments do not have to be terminated PHP.

**Comment by galloj** [comment]
This test causes error in PHP as expected https://ato.pxeger.com/run?1=m724IKNgwYKlpSVpuhY3zWzsgVyulNTknMSiVI3ikqLM5JL4ksqC1GJbQ01rLn0thYzUnJx8hZKM1KJURUVFLi4rTS4uiG6oITDDAA

Or do you mean something else?

**Comment by xpavlic** [comment]
In w3school php compiler it was just a warning.

**Comment by galloj** [comment]
W3school is probably using PHP 7 or older it seems.
